const API = {
	Bucket:'cscb-1259085570',
	Region:'ap-chengdu',
	http:'http://cscb2.kelinteng.com',
	https:'https://cscb2.kelinteng.com',
	UPLOAD_HOST:'http://txcos.kelinteng.com/',
	//0.获取省市县接口
    getAreaData:'area/areaData',
	//1.登陆接口
	login:'wemini/login',
	//1.注册接口
	register:'wemini/register',
	//2.首页-广告接口
	adlist:'wemini/adlist',
	//3.挂单推荐列表
	getTaskList:'wemini/getTaskList',
	//4.市场-挂单分类
	getTaskCategoryList:'wemini/getTaskCategoryList',
	//5.市场-挂单列表
	getTaskList:'wemini/getTaskList',
	//6.挂单详情-挂单数据
	taskDetail:'wemini/taskDetail',
	//7.挂单详情-报价列表
	taskDetailLog:'wemini/taskDetailLog',
	//8.挂单详情-服务进程
	taskDetailTimeLine:'wemini/taskDetailTimeLine',
	//9.挂单详情-查看报价
	lookbidlog:'wemini/lookbidlog',
	//10.确认订单-获取数据
	sureorder:'wemini/sureorder',
	//11.确认订单-提交订单
	postOrder:'wemini/postOrder',
	//12.支付结果-支付数据
	payResult:'wemini/payResult',
	//13.发布-快速发布-获取挂单数据
	taskDetail:'wemini/taskDetail',
	//14.发布-快速发布-提交发布
	fastbid:'wemini/fastbid',
	//15.发布-精准发布-获取挂单数据
	taskDetail:'wemini/taskDetail',
	//16.发布-精准发布-提交发布
	publishbid:'wemini/publishbid',
	//17.发布-获取服务类型
	bidCategoryList:'wemini/bidCategoryList',
	//18.发布-获取用户车辆信息
	getCarNew:'wemini/getCarNew',
	//19.报价-获取报价数据
	taskLogDetail:'wemini/taskLogDetail',
	//20获取临时密钥
	qcloud_key:'wemini/qcloud_key',
	//21.通用-上传图片
	//22.报价-获取报价数据
	bidding:'wemini/bidding',
	//23.我的发布-统计数据
	myPubData:'wemini/myPubData',
	//24.我的发布-挂单列表
	myTaskList:'wemini/myTaskList',
	//25.我的发布-关闭服务
	closeTask:'wemini/closeTask',
	//26.判断是否是商家
	isSeller:'wemini/isSeller',
	//27.判断是否已报价
	isBidding:'wemini/isBidding',
	//28.扫码核销
	scanTask:'wemini/scanTask',
	//29.商家主页接口
	seller:'wemini/seller',
	//30.商家主页-我的竞标记录
	getCYTaskList:'wemini/getCYTaskList',
	//31.商家主页-我的服务记录
	getMyServiceList:'wemini/getMyServiceList',
	//32.商家主页-我的收益记录
	getMyIncomeList:'wemini/getMyIncomeList',
	//33.上报
	logcscb:'wemini/logcscb',
	//34.商家-服务类型
	gettypelist:'wemini/gettypelist',
	//35.商家-商家列表
	getSellerList:'wemini/sellerlist',
	//36.商家主页
	sellerinfo:'wemini/sellerinfo',
}	
export default API